trigger: 
  - master

pr: none

pool:
  vmImage: ubuntu-18.04

variables:
  # Container registry service connection established during pipeline creation
- name: dockerfilePath
  value: '$(Build.SourcesDirectory)/Dockerfile'
- name: tag
  value: '$(Build.BuildId)'
  # Agent VM image name
- group: macsCampingGroup

