pr: none

pool:
  vmImage: ubuntu-18.04

variables:
  # Container registry service connection established during pipeline creation

- name: tag
  value: '$(Build.BuildId)'
  # Agent VM image name
- group: macsCampingGroup

steps:
- task: DotNetCoreCLI@2
  name: build
  displayName: Build Web App
  inputs:
    command: build
    configuration: Release
    
- task: DotNetCoreCLI@2
  name: publishAppPackage
  displayName: Get App Package for Deployment
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '-o $(Build.ArtifactStagingDirectory)/Output'
    zipAfterPublish: true

- task: AzureRmWebAppDeployment@4
  displayName: Deploy Mac's Website
  name: deployWebApp
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Enterprise(9661a81b-1bc6-4836-ad63-41ddb2515f1b)'
    appType: 'webAppLinux'
    WebAppName: macscampingarea
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    RuntimeStack: 'DOTNETCORE|2.1'
    StartupCommand: dotnet MacsASPNETCore.dll

- task: AzureAppServiceSettings@1
  name: configureApp
  displayName: Configure Website
  inputs:
    azureSubscription: 'Visual Studio Enterprise(9661a81b-1bc6-4836-ad63-41ddb2515f1b)'
    appName: 'macscampingarea'
    resourceGroupName: 'macscampinggroup'
    appSettings: |
      {
        "ApplicationInsights": {
            "InstrumentationKey": "c3ccdba0-dfc0-49ed-aeff-298c09564342"
        },
        "Logging": {
            "IncludeScopes": false,
            "LogLevel": {
                "Default": "Warning",
                "System": "Information",
                "Microsoft": "Information"
            }
        },
        "Azure": {
            "KeyVault": {
                "Vault": "macscampvault",
                "ClientId": "e8725941-c27a-4012-8c89-19aca10b11a5",
                "ClientSecret": "$(client-secret)"
            }
        },
        "AppSettings": {
            "AdminEmail": "admin@macscampingarea.com",
            "AdminPassword": "$(AppSettings--AdminPassword)",
            "SiteEmailAddress": "ian.cornett@gmail.com",
            "InfoEmailAddress": "info@macscampingarea.com",
            "SendGridAPIKey": "$(AppSettings--SendGridAPIKey)",
            "FacebookAppId": "$(FacebookAppId)",
            "FacebookAppSecret": "$(FacebookAppSecret)"
        },
        "Data": {
            "ActivityDb": "$(Data--ActivityDb)"
        }
      }