pr: none

pool:
  vmImage: ubuntu-18.04

variables:
  # Container registry service connection established during pipeline creation

- name: tag
  value: '$(Build.BuildId)'
  # Agent VM image name
- group: macsCampingGroup

steps:
- task: DotNetCoreCLI@2
  name: build
  displayName: Build Web App
  inputs:
    command: build
    configuration: Release
    
- task: DotNetCoreCLI@2
  name: publishAppPackage
  displayName: Get App Package for Deployment
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '-o $(Build.ArtifactStagingDirectory)/Output'
    zipAfterPublish: true

- task: AzureRmWebAppDeployment@4
  displayName: Deploy Mac's Website
  name: deployWebApp
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Enterprise(9661a81b-1bc6-4836-ad63-41ddb2515f1b)'
    appType: 'webAppLinux'
    WebAppName: macscampingarea
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    StartupCommand: dotnet MacsASPNETCore.dll      

- task: AzureAppServiceSettings@1
  name: configureApp
  displayName: Configure Website
  inputs:
    azureSubscription: 'Visual Studio Enterprise(9661a81b-1bc6-4836-ad63-41ddb2515f1b)'
    appName: 'macscampingarea'
    resourceGroupName: 'macscampinggroup'
    appSettings: |
      [
        {
          "name": "APPINSIGHTS_INSTRUMENTATIONKEY",
          "value": "c3ccdba0-dfc0-49ed-aeff-298c09564342",
          "slotSetting": false
        },
        {
            "name": "AdminEmail",
            "value": "admin@macscampingarea.com",
            "slotSetting": false
        },
        {
            "name": "AdminPassword",
            "value": "$(AppSettings--AdminPassword)",
            "slotSettings": false
        },
        {
            "name": "SiteEmailAddress",
            "value": "ian@digitaldelirium.tech",
            "slotSetting": false
        },
        {
            "name": "InfoEmailAddress",
            "value": "info@macscampingarea.com",
            "slotSetting": false
        },
        {
            "name": "SendGridAPIKey",
            "value": "$(AppSettings--SendGridAPIKey)",
            "slotSetting": false
        },
        {
            "name": "FacebookAppId",
            "value": "$(FacebookAppId)",
            "slotSetting": false
        },
        {
            "name": "FacebookAppSecret",
            "value": "$(FacebookAppSecret)",
            "slotSetting": false
        },
        {
            "name": "Data_ActivityDb",
            "value": "$(Data--ActivityDb)",
            "slotSetting": false
        },
        {
            "name": "linuxFxVersion",
            "value": "DOTNET|2.1",
            "slotSetting": false
        }
      ]
