version: '3'

services:
  macsaspnetcore:
    image: macsaspnetcore
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80"
      - "443"
    deploy:
      replicas: 1
      restart_policy: always
  macsdb:
    image: 
